'use client';

const TermsAndConditions = () => {
  return (
    <div className="w-full h-full bg-brand-green">
    <div className="mx-auto max-w-4xl px-4 py-16 lg:py-32 bg-brand-green">
      {' '}
      <h1 className="mb-6 text-3xl lg:text-5xl font-bold">
        Sloane Terms and Conditions
      </h1>{' '}
      <p className="mb-16">
        Welcome to Sloane. Our Terms and Conditions ("Terms") for the Sloane platform. By subscribing, you agree to these Terms. We ask that you
        please read them carefully. If you have any questions, feel free to
        contact us at{' '}
        <a href="mailto:support@sloane.biz" className="text-brand-logo">
          support@sloane.biz
        </a>
        .
      </p>
      <div className="mb-4">
        <h2 className="mb-2 text-2xl font-semibold">1. Subscription Details</h2>
        <p className="mb-2">
          <strong>Plan:</strong> Sloane offers one subscription plan at $79
          every 28 days, referred to here as "monthly."
        </p>
        <p>
          <strong>Billing:</strong> Your payment will be charged on the day you
          sign up and will recur every 28 days via direct debit through a Stripe
          subscription.
        </p>
      </div>
      <div className="mb-4">
        <h2 className="mb-2 text-2xl font-semibold">2. Cancellation Policy</h2>
        <p>
          <strong>Cancel Anytime:</strong> You can cancel your subscription at
          any time by emailing{' '}
          <a href="mailto:support@sloane.biz" className="text-blue-500">
            support@sloane.biz
          </a>
          Notification needs to be received 7 days before your next billing date. 
        Your cancellation will be processed within 7 days and you can continue to use the platform until your subscription period ends.
        </p>
      </div>
      <div className="mb-4">
        <h2 className="mb-2 text-2xl font-semibold">3. Refunds</h2>
        <p>
          <strong>Refunds:</strong> We do not offer refunds. If you decide Sloane is not for you, simply cancel your subscription by emailing{' '}
          <a href="mailto:support@sloane.biz" className="text-blue-500">
            support@sloane.biz
          </a>
          , and you can walk away, no questions asked.
        </p>
      </div>
      <div className="mb-4">
        <h2 className="mb-2 text-2xl font-semibold">
          4. User Conduct and Responsibility
        </h2>
        <p>
          <strong>Content Suggestions:</strong> All information and content
          provided by Sloane's platform are considered suggestions. It is the
          user's responsibility to verify and use this information. Sloane is
          not responsible for how you use the content generated by the platform.
        </p>
      </div>
      <div className="mb-4">
        <h2 className="mb-2 text-2xl font-semibold">5. Data Privacy</h2>
        <p>
          <strong>Privacy Policy:</strong> We handle data privacy seriously and
          store all information within our secure database. Your information, as well as the content produced within Sloane is housed on an internal database. This means that any external Ai, for exmaple, chatGPT, does not and can not have access to your data. For more details,
          please refer to our{' '}
          <a href="#" className="text-blue-500">
            Privacy Policy
          </a>
          .
        </p>
      </div>
      <div className="mb-4">
        <h2 className="mb-2 text-2xl font-semibold">
          6. Support and Maintenance
        </h2>
        <p>
          <strong>Chatbot Support:</strong> Starting in August 2024, we will
          offer support through a trained chatbot within the app. Until then,
          for any support, please email us at{' '}
          <a href="mailto:support@sloane.biz" className="text-blue-500">
            support@sloane.biz
          </a>
          .
        </p>
        <p>
          <strong>Maintenance Notifications:</strong> Our platform may
          occasionally be down for maintenance and upgrades. However, members
          will always be notified in advance of any planned downtime.
        </p>
      </div>
      <div className="mb-4">
        <h2 className="mb-2 text-2xl font-semibold">
          7. Modifications to Terms
        </h2>
        <p>
          <strong>Updates:</strong> Sloane reserves the right to modify these
          Terms. Users will be notified of any changes through a Terms and
          Conditions popup inside the platform.
        </p>
      </div>
      <div className="mb-4">
        <h2 className="mb-2 text-2xl font-semibold">
          8. Disclaimer of Liability
        </h2>
        <p>
          <strong>Usage Responsibility:</strong> Sloane is not responsible for
          how you use the information and content provided by the platform. All
          content is generated by the ChatGPT API and should be treated as
          suggestions. Users are required to conduct their own due diligence.
        </p>
      </div>
     
      <p>
        <strong>Last Updated:</strong> [Insert Date]
      </p>
      <p>
        For any inquiries or support, please contact{' '}
        <a href="mailto:support@sloane.biz" className="text-blue-500">
          support@sloane.biz
        </a>
        .
      </p>
    </div>
    </div>
  );
};

export default TermsAndConditions;
