'use client';

const TermsAndConditions = () => {
  return (
    <div className="h-full w-full">
      <div className="w-full bg-brand-green py-16 lg:py-32">
        <div className="mx-auto max-w-4xl px-4">
          <h1 className="text-center text-3xl font-bold text-brand-cream lg:text-5xl">
            Sloane Terms and Conditions
          </h1>
        </div>
      </div>
      <div className="bg-brand-cream py-16">
        <div className="mx-auto max-w-[1440px] px-4">
          <p className="mb-16 text-center px-4 lg:px-32 text-brand-green-dark">
            Welcome to Sloane. Our Terms and Conditions ("Terms") for the Sloane
            platform. By subscribing, you agree to these Terms. We ask that you
            please read them carefully. If you have any questions, feel free to
            contact us at{' '}
            <span className="text-brand-green">
              <a href="mailto:support@sloane.biz">support@sloane.biz</a>
            </span>
            .
          </p>
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
            {termsData.map((term, index) => (
              <div key={index} className="rounded-lg border-2 border-brand-green">
                <div className="bg-brand-green p-4 rounded-t-md">
                  <h2 className="mb-2 text-2xl font-semibold text-brand-cream">
                    {term.title}
                  </h2>
                </div>
                <div className="bg-brand-cream p-4 rounded-b-lg">
                  <p
                    className="text-brand-green-dark"
                    dangerouslySetInnerHTML={{ __html: term.content }}
                  ></p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

const termsData = [
  {
    title: '1. Subscription Details',
    content:
      " Sloane offers one subscription plan at $79 every 28 days, referred to here as 'monthly.'<br/><br/> Your payment will be charged on the day you sign up and will recur every 28 days via direct debit through a Stripe subscription.",
  },
  {
    title: '2. Cancellation Policy',
    content:
      'You can cancel your subscription at any time by emailing <span class="text-brand-green">support@sloane.biz</span>. Notification needs to be received 7 days before your next billing date. <br/><br/>Your cancellation will be processed within 7 days and you can continue to use the platform until your subscription period ends.',
  },
  {
    title: '3. Refunds',
    content:
      ' We do not offer refunds. If you decide Sloane is not for you, simply cancel your subscription by emailing <span class="text-brand-green">support@sloane.biz</span>, and you can walk away, no questions asked.',
  },
  {
    title: '4. User Conduct and Responsibility',
    content:
      " All information and content provided by Sloane's platform are considered suggestions. It is the user's responsibility to verify and use this information.<br/><br/> Sloane is not responsible for how you use the content generated by the platform.",
  },
  {
    title: '5. Data Privacy',
    content:
      ' We handle data privacy seriously and store all information within our secure database. Your information, as well as the content produced within Sloane, is housed on an internal database. <br/><br/>This means that any external Ai, for example, chatGPT, does not and can not have access to your data. For more details, please refer to our Privacy Policy.',
  },
  {
    title: '6. Support and Maintenance',
    content:
      'Starting in August 2024, we will offer support through a trained chatbot within the app. Until then, for any support, please email us at <span class="text-brand-green">support@sloane.biz</span>. <br/><br/> Our platform may occasionally be down for maintenance and upgrades. However, members will always be notified in advance of any planned downtime.',
  },
  {
    title: '7. Modifications to Terms',
    content:
      'Sloane reserves the right to modify these Terms. Users will be notified of any changes through a Terms and Conditions popup inside the platform.',
  },
  {
    title: '8. Disclaimer of Liability',
    content:
      'Sloane is not responsible for how you use the information and content provided by the platform. All content is generated by the ChatGPT API and should be treated as suggestions. Users are required to conduct their own due diligence.',
  },
  {
    title: 'Inquiries & support',
    content: 'For any inquiries or support, please contact <span class="text-brand-green">support@sloane.biz</span>',
  },
];

export default TermsAndConditions;
